pkl_path: "/tmp/input_df.pkl"
input_table_spec:
  table_name: ecom_cb_input_data
  table_sample: 90
  eval_table_sample: 10
model:
  DiscreteDQN:
    trainer_param:
      actions:
      - Bacon
      - Ribs
      rl:
        gamma: 0.0  # zero gamma for bandit setting
        target_update_rate: 1.0
        maxq_learning: true
        temperature: 0.35
        softmax_policy: false
        q_network_loss: mse
      double_q_learning: true
      minibatch_size: 128
      minibatches_per_step: 1
      optimizer:
        Adam:
          lr: 0.01
    eval_parameters:
      calc_cpe_in_training: true
    net_builder:
      FullyConnected:
        sizes: []
        activations: []
    cpe_net_builder:
      FullyConnected:
        sizes: []
        activations: []
    preprocessing_options:
      num_samples: 1000
num_epochs: 10
publisher:
  FileSystemPublisher: {}
