%YAML 1.2
---
env: CartPole-v0
pkl_path: tmp_pickle.pkl
input_table_spec:
  table_name: test_table
  output_dataset:
    parquet_url: tmp_parquet
model:
  DiscreteDQN:
    trainer_param:
      actions:
      - 4
      - 5
      states:
      - 0
      - 1
      - 2
      - 3
      metrics:
      - reward
      rl:
        gamma: 0.99
        epsilon: 0.05
        target_update_rate: 0.1
        maxq_learning: true
        temperature: 0.35
        softmax_policy: false
        q_network_loss: mse
      double_q_learning: true
      minibatch_size: 512
      minibatches_per_step: 1
      optimizer:
        optimizer: ADAM
        learning_rate: 0.01
        l2_decay: 0
      evaluation:
        calc_cpe_in_training: false
    net_builder:
      FullyConnected:
        sizes:
        - 128
        - 64
        activations:
        - relu
        - relu
    preprocessing_options:
      num_samples: 1000
num_episodes: 100
max_steps: 200
seed: 42

# training params
use_gpu: false
num_epochs: 1
reward_options:
  custom_reward_expression:
validator:
  NoValidation: {}
publisher:
  NoPublishing: {}