env_name: CartPole-v0
model_path: "cartpole_batch_rl_model.torchscript"
pkl_path: "/tmp/tmp_pickle.pkl"
input_table_spec:
  table_name: test_table
  table_sample: 90
  eval_table_sample: 10
model:
  DiscreteDQN:
    trainer_param:
      actions:
      - 0
      - 1
      rl:
        gamma: 0.99
        epsilon: 0.2
        target_update_rate: 0.1
        maxq_learning: true
        temperature: 0.35
        softmax_policy: false
        q_network_loss: mse
      double_q_learning: true
      minibatch_size: 512
      minibatches_per_step: 1
      optimizer:
        optimizer: ADAM
        learning_rate: 0.01
        l2_decay: 0.01
      evaluation:
        calc_cpe_in_training: true
    net_builder:
      FullyConnected:
        sizes:
        - 128
        - 64
        activations:
        - relu
        - relu
    cpe_net_builder:
      FullyConnected:
        sizes:
        - 128
        - 64
        activations:
        - relu
        - relu
    preprocessing_options:
      num_samples: 1000
num_episodes_for_data_batch: 150
max_steps: 200
seed: 42

# training params
use_gpu: false
num_train_epochs: 20
reward_options:
  custom_reward_expression:
validator:
  NoValidation: {}
publisher:
  NoPublishing: {}

# evaluation
eval_temperature: 0.1
num_eval_episodes: 50
passing_score_bar: 120
