env_name: Pendulum-v0
model_path: "pendulum_batch_rl_model.torchscript"
pkl_path: "/tmp/tmp_pickle.pkl"
input_table_spec:
  table_name: test_table
  table_sample: 100
  eval_table_sample: 0
model:
  SoftActorCritic:
    trainer_param:
      rl:
        gamma: 0.9
        target_update_rate: 0.5
      entropy_temperature: 0.01
      minibatch_size: 1024
      q_network_optimizer:
        optimizer: ADAM
        learning_rate: 0.001
        l2_decay: 0
      value_network_optimizer:
        optimizer: ADAM
        learning_rate: 0.001
        l2_decay: 0
      actor_network_optimizer:
        optimizer: ADAM
        learning_rate: 0.001
        l2_decay: 0
      alpha_optimizer: null
    actor_net_builder:
      GaussianFullyConnected:
        sizes:
        - 64
        - 64
        activations:
        - leaky_relu
        - leaky_relu
    critic_net_builder:
      FullyConnected:
        sizes:
        - 64
        - 64
        activations:
        - leaky_relu
        - leaky_relu
    value_net_builder:
      FullyConnected:
        sizes:
        - 64
        - 64
        activations:
        - leaky_relu
        - leaky_relu
    state_preprocessing_options:
      num_samples: 20000
    action_preprocessing_options:
      num_samples: 20000
    action_float_features: [[0, "0"]]
    eval_parameters:
      calc_cpe_in_training: false

num_episodes_for_data_batch: 200
max_steps: 200
seed: 42

use_gpu: false
num_train_epochs: 80
reward_options:
  custom_reward_expression:
validator:
  NoValidation: {}
publisher:
  NoPublishing: {}

# TODO: remove, evaluation temperature is not relevant here
eval_temperature: 0.1
num_eval_episodes: 30
passing_score_bar: -750
